{ // JobNames
JobName = [
["Новичок","Novice"]
,["Мечник","Swordman"]
,["Вор","Thief"]
,["Послушник","Acolyte"]
,["Лучник","Archer"]
,["Маг","Mage"]
,["Торговец","Merchant"]
,["Рыцарь","Knight"]
,["Убийца","Assassin"]
,["Священник","Priest"]
,["Охотник","Hunter"]
,["Волшебник","Wizard"]
,["Кузнец","Blacksmith"]
,["Крестоносец","Crusader"]
,["Разбойник","Rogue"]
,["Монах","Monk"]
,["Бард","Bard"]
,["Танцовщица","Dancer"]
,["Мудрец","Sage"]
,["Алхимик","Alchemist"]
,["Суперновичок","Super Novice"]
,["Командор","Lord Knight"]
,["Ассасин","Assassin Cross"]
,["Епископ","High Priest"]
,["Снайпер","Sniper"]
,["Архимаг","High Wizard"]
,["Оружейник","Mastersmith"]
,["Паладин","Paladin"]
,["Сталкер","Stalker"]
,["Мистик","Champion"]
,["Менестрель","Minstrel"]
,["Цыганка","Gypsy"]
,["Профессор","Scholar"]
,["Биохимик","Biochemist"]
,["Ст. Новичок","High Novice"]
,["Ст. Мечник","High Swordman"]
,["Ст. Вор","High Thief"]
,["Ст. Послушник","High Acolyte"]
,["Ст. Лучник","High Archer"]
,["Ст. Маг","High Magician"]
,["Ст. Торговец","High Merchant"]
,["Таэквондист","Taekwon Kid"]
,["Гладиатор","Teakwon Master"]
,["Медиум","Soul Linker"]
,["Ниндзя","Ninja"]
,["Стрелок","Gunslinger"]
,["Рунмейстер","Rune Knight (non-trans)"]
,["Рунмейстер","Rune Knight (trans)"]
,["Каратель","Glt Cross (non-trans)"]
,["Каратель","Glt Cross (trans)"]
,["Архиепископ","Arch Bishop (non-trans)"]
,["Архиепископ","Arch Bishop (trans)"]
,["Рейнджер","Ranger (non-trans)"]
,["Рейнджер","Ranger (trans)"]
,["Чародей","Warlock (non-trans)"]
,["Чародей","Warlock (trans)"]
,["Механик","Mechanic (non-trans)"]
,["Механик","Mechanic (trans)"]
,["Тамплиер","Royal Guard (non-trans)"]
,["Тамплиер","Royal Guard (trans)"]
,["Преследователь","Shadow Chaser (non-trans)"]
,["Преследователь","Shadow Chaser (trans)"]
,["Отшельник","Sura (non-trans)"]
,["Отшельник","Sura (trans)"]
,["Маэстро","Maestro (non-trans)"]
,["Маэстро","Maestro (trans)"]
,["Муза","Wanderer (non-trans)"]
,["Муза","Wanderer (trans)"]
,["Элементалист","Sorcerer (non-trans)"]
,["Элементалист","Sorcerer (trans)"]
,["Генетик","Geneticist (non-trans)"]
,["Генетик","Geneticist (trans)"]
,["Кагеро/Оборо","Kagero/Oboro"]
,["Суперновичок 2","Expanded Super Novice"]
,["Мятежник","Rebellion"]
,["Призыватель","Summoner"]
,["Звездный император","Star Emperor"]
,["Жнец душ","Soul Reaper"]
];
}
