{ // MapNames
MAP_NAME = [
["","All Maps"]
,["","Prontera Fields"]
,["","Prontera Culvert"]
,["","Labyrinth Forest"]
,["","Undersea Tunnel"]
,["","Morocc Fields"]
,["","Pyramid Dungeon"]
,["","Sphinx Dungeon"]
,["","Ant Hell"]
,["","Geffen Fields"]
,["","Geffen Dungeon"]
,["","Geffenia"]
,["","Orc Dungeon"]
,["","Glast Heim"]
,["","Glast Heim Lower"]
,["","Poring Island"]
,["","Payon Fields"]
,["","Payon Cave"]
,["��","Sunken Ship"]
,["","Mjolnir Fields"]
,["","Mjolnir Dead Pit"]
,["","Clock Tower"]
,["","Toy Factory"]
,["","Comodo Fields"]
,["","Comodo Dungeon"]
,["","Umbala Fields"]
,["","Umbala Dungeon"]
,["","Nifflheim Fields"]
,["","Guild Dungeons Baldur"]
,["","Guild Dungeons Luina"]
,["","Guild Dungeons Valkyrie"]
,["","Guild Dungeons Britoniah"]
,["","Turtle Dungeon"]
,["","Amatsu"]
,["","Kunlun"]
,["��","Louyang"]
,["","Ayotaya"]
,["","Juno Fields"]
,["","Magma Dungeon"]
,["","Doll Factory"]
,["","Einbroch Fields"]
,["","Mine Dungeon"]
,["","Lighthalzen Fields"]
,["","Somatology Laboratory"]
,["","Ruins of Juperos"]
,["","Hugel Fields"]
,["","Abyss Lake"]
,["","Thanatos Tower"]
,["","Odin Temple"]
,["","Rachel Fields"]
,["","Rachel Sanctuary"]
,["�","Ice Dungeon"]
,["","Veins Fields"]
,["","Thor Volcano"]
,["","Nameless Island"]
,["","Moscovia"]
,["��","Between Dimensions"]
,["","Guild Dungeons (Juno)"]
,["","Guild Dungeons (Rachel)"]
,["","Endless Tower"]
,["","Another world"]
,["","Nidhoggur Dungeon"]
,["","Outskirts of Kamidal Mountain"]
,["","Kamidal Tunnel"]
,["","Scaraba Hall"]
,["","Skarava hall"]
,["","Brasilis Field"]
,["","Brasilis Dungeon"]
,["","Overlook Water Dungeon"]
,["","Dewata"]
,["","Land of Heroes"]
,["","Isle of Bios"]
,["","Morse's Cave"]
,["","Nightmarish Jitterbug"]
,["","Temple of Demon God"]
,["","Faceworm Nest Dungeon"]
,["","Sara's Memory"]
,["","Hazy Forest"]
,["","Verus"]
,["","Charleston Crisis"]
,["","Old Glast Heim"]
,["","Geffen Magic Tournament"]
,["","Ghost Place"]
,["","Devil's Tower"]
,["","Assault on the Airship"]
,["","Fenrir and Sarah"]
,["","The Last Room"]
,["","The Royal Banquet"]
,["","Sky Fortress Invasion"]
,["","Room of Consciousness"]
,["","Nightmare Glast Heim"]
,["","Tomb of Honor(Bio5)"]
,["","Terra Gloria"]
,["","Werner Laboratory Central Room"]
,["","Heart Hunter War Base 2"]
,["","Rock Ridge"]
,["","Horror Toy Factory"]
,["","Nightmare Pyramids"]
,["","Undersea Tunnel (6 floor)"]
,["","Illusion of Moonlight"]
,["","Illusion of Vampire"]
,["","Illusion of Frozen"]
,["","Glast Heim Abyss"]
,["","Special Security Area Os"]
,["","Laboratory Waste Disposal Plant Rudus Floor 1"]
,["","Laboratory Waste Disposal Plant Rudus Floor 2"]
,["","Laboratory Waste Disposal Plant Rudus Floor 3"]
,["","Illusion"]
,["","Juno Norgroad Floor 3 (mag_dun03)"]
,["","Advanced Old Glast Heim"]
,["","Illusion of Teddy Bear (ein_d02_i)"]
,["","Illusion of Abyss Turtle Island (tur_d04_i)"]
,["","Illusion Labyrinth"]
,["","Illusion Luanda"]
,["","Infinite Space"]
,["","Edda Fall of Glast Heim (Normal)"]
,["","Edda Fall of Glast Heim (Hard)"]
,["","Edda Biolab"]
// ,["","Place_Holder"]
];
}
