{ // Status Ailments [AilmentsOBJ]
AilmentsOBJ = [
 ["отравить","Poison"]
,["оглушению","Stun"]
,["Заморозка","Freeze"]
,["проклятию","Curse"]
,["слепоте ","Blind"]
,["сну","Sleep"]
,["молчанию","Silence"]
,["Хаос","Chaos"]
,["кровотечению","Bleeding"]
,["Окаменение","Stone"]
,["Перерыв оружия","Weapon Break"]
,["Прорыв брони","Armor Break"]
,["Глубокого сна","Deep Sleep"]
,["Печать яда","Venom Impress"]
,["Бездонная топь","Marsh of Abyss"]
,["Поджечь","Burning"]
,["Обморожение","Cristallization"]
,["Элегия","Gloomy Day"]
,["Темный коготь","Dark Claw"]
,["Эвристический анализ","Analyze"]
,["Испуг","Sightless Mind"]
];
}